name: Timestamp

on:
  push:
    branches: [master]

  schedule:
    - cron: '*/20 * * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Debug Information
        run: echo "::debug::Triggered by ref = ${{github.ref}}"

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Update Timestamp File
        run: |
          current_time=$(date '+%Y-%m-%d %H:%M:%S')
          echo "Updated on $current_time" > tmp.txt

      - name: Setup Git Configuration
        run: |
          git config user.email "fool-body-cheddar@duck.com"
          git config user.name "recitativonika"

      - name: Prepare Commit
        run: |
          commit_messages=("Update" "Renew" "Revise" "Change" "Modify")
          random_msg=${commit_messages[$RANDOM % ${#commit_messages[@]}]}

          git add tmp.txt
          git commit -m "$random_msg - $current_time" || echo "No changes to commit."

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: '.'
          github_token: ${{ secrets.GITHUB_TOKEN }}
